apiVersion: v1
kind: Pod
metadata:
 name: grafana
 labels:
  type: grafana
spec:
 containers:
 - name: grafana
   image: grafana/grafana:latest
   imagePullPolicy: Never
   ports:
   - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
spec:
  selector:
    type: grafana
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30004
      protocol: TCP