apiVersion: v1
kind: Pod
metadata:
 name: mysql
 labels:
  type: mysql
spec:
 containers:
 - name: mysql
   image: mysql:latest
   imagePullPolicy: Never
   env:
   - name: MYSQL_ROOT_PASSWORD
     value: Admin@123
   - name: MYSQL_DATABASE
     value: feature_toggle_dev
   ports:
   - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  selector:
    type: mysql
  type: NodePort
  ports:
    - port: 3306
      targetPort: 3306
      nodePort: 30002
      protocol: TCP