apiVersion: v1
kind: Pod
metadata:
 name: postgres
 labels:
  type: postgres
  'backstage.io/kubernetes-id': energy-solution
spec:
 containers:
 - name: postgres
   image: postgres:latest
   imagePullPolicy: Never
   env:
   - name: POSTGRES_PASSWORD
     value: mysecretpassword
   ports:
   - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    'backstage.io/kubernetes-id': energy-solution
spec:
  selector:
    type: postgres
  type: NodePort
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: 30010
      protocol: TCP